### ISSUE TITLE
fopen() timeout

### ISSUE THREAD

**Issue by jjwwcc** [humhub-contrib/auth-google#5]
php.ini  fopen() has been set to On.
but always fail.
I also test fopen() not by yii. It works well. I can't still find why it is wrong.
Thank you

```yii\base\ErrorException: fopen(https://accounts.google.com/o/oauth2/token): failed to open stream: Connection timed out in /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/StreamTransport.php:61
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'fopen(https://a...', '/var/www/humhub...', 61, Array)
#1 /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/StreamTransport.php(61): fopen('https://account...', 'rb', false, Resource id #22)
#2 /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/Client.php(233): yii\httpclient\StreamTransport->send(Object(yii\httpclient\Request))
#3 /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/Request.php(445): yii\httpclient\Client->send(Object(yii\httpclient\Request))
#4 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php(230): yii\httpclient\Request->send()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/OAuth2.php(149): yii\authclient\BaseOAuth->sendRequest(Object(yii\httpclient\Request))
#6 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(415): yii\authclient\OAuth2->fetchAccessToken('4/0AX4XfWhxF2Xr...')
#7 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(226): yii\authclient\AuthAction->authOAuth2(Object(humhubContrib\auth\google\authclient\GoogleAuth), Array)
#8 /var/www/humhub/protected/humhub/modules/user/authclient/AuthAction.php(38): yii\authclient\AuthAction->auth(Object(humhubContrib\auth\google\authclient\GoogleAuth))
#9 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(210): humhub\modules\user\authclient\AuthAction->auth(Object(humhubContrib\auth\google\authclient\GoogleAuth))
#10 [internal function]: yii\authclient\AuthAction->run()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Action->runWithParams(Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('external', Array)
#14 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('user/auth/exter...', Array)
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#16 /var/www/humhub/index.php(25): yii\base\Application->run()
#17 {main}

Next yii\httpclient\Exception: fopen(https://accounts.google.com/o/oauth2/token): failed to open stream: Connection timed out in /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/StreamTransport.php:68
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/Client.php(233): yii\httpclient\StreamTransport->send(Object(yii\httpclient\Request))
#1 /var/www/humhub/protected/vendor/yiisoft/yii2-httpclient/src/Request.php(445): yii\httpclient\Client->send(Object(yii\httpclient\Request))
#2 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php(230): yii\httpclient\Request->send()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/OAuth2.php(149): yii\authclient\BaseOAuth->sendRequest(Object(yii\httpclient\Request))
#4 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(415): yii\authclient\OAuth2->fetchAccessToken('4/0AX4XfWhxF2Xr...')
#5 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(226): yii\authclient\AuthAction->authOAuth2(Object(humhubContrib\auth\google\authclient\GoogleAuth), Array)
#6 /var/www/humhub/protected/humhub/modules/user/authclient/AuthAction.php(38): yii\authclient\AuthAction->auth(Object(humhubContrib\auth\google\authclient\GoogleAuth))
#7 /var/www/humhub/protected/vendor/yiisoft/yii2-authclient/src/AuthAction.php(210): humhub\modules\user\authclient\AuthAction->auth(Object(humhubContrib\auth\google\authclient\GoogleAuth))
#8 [internal function]: yii\authclient\AuthAction->run()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Action->runWithParams(Array)
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('external', Array)
#12 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('user/auth/exter...', Array)
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(humhub\components\Request))
#14 /var/www/humhub/index.php(25): yii\base\Application->run()
#15 {main}```

**Comment by ArchBlood** [comment]
Seems related to https://github.com/yiisoft/yii2-httpclient/issues/38, did you make any changes other than enabling `fopen()`?
